/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.presensikaryawan.mainForm;

import com.presensikaryawan.departmentSetting.DepartmentForm;
import com.presensikaryawan.gajiPerKaryawanReport.GajiPerKaryawanReportForm;
import com.presensikaryawan.golongan.GolonganForm;
import com.presensikaryawan.groupShift.GroupShiftForm;
import com.presensikaryawan.karyawan.KaryawanForm;
import com.presensikaryawan.liburNasional.LiburNasionalForm;
import com.presensikaryawan.liburPerusahaan.LiburPerusahaanForm;
import com.presensikaryawan.outletSetting.OutletForm;
import com.presensikaryawan.payrollBankReport.PayrollBankReportForm;
import com.presensikaryawan.posisi.PosisiForm;
import com.presensikaryawan.rekapHistoriGajiReport.RekapGajiForm;
import com.presensikaryawan.rekapPresensi.RekapPresensiForm;
import com.presensikaryawan.rekapPresensiPerBulanReport.RekapPresensiPerBulanForm;
import com.presensikaryawan.shiftSetting.ShiftForm;
import com.presensikaryawan.statusSetting.StatusSettingForm;
import com.presensikaryawan.transaksiDepartment.TransaksiDepartmentForm;
import com.presensikaryawan.transaksiGajiDepartmentTotalReport.TransaksiGajiDepartmentReportForm;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tinus
 */
public class MainForm extends javax.swing.JFrame {

    RekapPresensiForm rekapPresensiForm;
    TransaksiDepartmentForm transaksiDepartmentForm;
    PayrollBankReportForm payrollBankReportForm;
    TransaksiGajiDepartmentReportForm transaksiGajiDepartmentReportForm;
    GolonganForm golonganForm;
    ShiftForm shiftForm;
    GajiPerKaryawanReportForm gajiPerKaryawanReportForm;
    RekapPresensiPerBulanForm rekapPresensiPerBulanForm;
    RekapGajiForm rekapGajiForm;
    DepartmentForm departmentForm;
    OutletForm outletForm;
    PosisiForm posisiForm;
    GroupShiftForm groupShiftForm;
    StatusSettingForm statusSettingForm;
    KaryawanForm karyawanForm;
    LiburNasionalForm liburNasionalForm;
    LiburPerusahaanForm liburPerusahaanForm;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            rekapPresensiForm = new RekapPresensiForm(this, menuItemTransaksiPresensi);
            transaksiDepartmentForm = new TransaksiDepartmentForm(this, menuItemTransaksiGaji);
            payrollBankReportForm = new PayrollBankReportForm(this, menuItemPayrollBank);
            transaksiGajiDepartmentReportForm = new TransaksiGajiDepartmentReportForm(this, menuItemLaporanGajiTotalReport);
            gajiPerKaryawanReportForm = new GajiPerKaryawanReportForm(this, menuItemSlipGajiReport);
            rekapPresensiPerBulanForm = new RekapPresensiPerBulanForm(this, menuItemRekapPresensi);
            outletForm = new OutletForm(this, menuItemMasterOutlet);
            departmentForm = new DepartmentForm(this, menuItemMasterDepartment);
            rekapGajiForm = new RekapGajiForm(this);
            shiftForm = new ShiftForm(this, menuItemMasterShift);
            golonganForm = new GolonganForm(this, menuItemMasterGolongan);
            posisiForm = new PosisiForm(this, menuItemMasterPosisi);
            groupShiftForm = new GroupShiftForm(this, menuItemMasterGroupShift);
            statusSettingForm = new StatusSettingForm(this, menuItemMasterStatus);
            karyawanForm = new KaryawanForm(this, menuItemMasterKaryawan);
            liburNasionalForm = new LiburNasionalForm(this, menuItemMasterLiburNasional);
            liburPerusahaanForm = new LiburPerusahaanForm(this, menuItemMasterLiburPerusahaan);
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        picLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        transaksiMenu = new javax.swing.JMenu();
        menuItemTransaksiPresensi = new javax.swing.JMenuItem();
        menuItemTransaksiGaji = new javax.swing.JMenuItem();
        reportMenu = new javax.swing.JMenu();
        menuItemSlipGajiReport = new javax.swing.JMenuItem();
        menuItemLaporanGajiTotalReport = new javax.swing.JMenuItem();
        menuItemRekapPresensi = new javax.swing.JMenuItem();
        menuItemPayrollBank = new javax.swing.JMenuItem();
        menuItemHistoryGajiReport = new javax.swing.JMenuItem();
        masterMenu = new javax.swing.JMenu();
        menuItemMasterDepartment = new javax.swing.JMenuItem();
        menuItemMasterGolongan = new javax.swing.JMenuItem();
        menuItemMasterOutlet = new javax.swing.JMenuItem();
        menuItemMasterPosisi = new javax.swing.JMenuItem();
        menuItemMasterShift = new javax.swing.JMenuItem();
        menuItemMasterGroupShift = new javax.swing.JMenuItem();
        menuItemMasterStatus = new javax.swing.JMenuItem();
        menuItemMasterKaryawan = new javax.swing.JMenuItem();
        menuItemMasterLiburNasional = new javax.swing.JMenuItem();
        menuItemMasterLiburPerusahaan = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        picLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dssbackground1024.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLabel)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 659, Short.MAX_VALUE)
        );

        menuBar.setText("File");

        transaksiMenu.setText("Transaksi");

        menuItemTransaksiPresensi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemTransaksiPresensi.setText("Transaksi Presensi Karyawan");
        menuItemTransaksiPresensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTransaksiPresensiActionPerformed(evt);
            }
        });
        transaksiMenu.add(menuItemTransaksiPresensi);

        menuItemTransaksiGaji.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemTransaksiGaji.setText("Transaksi Gaji Karyawan");
        menuItemTransaksiGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTransaksiGajiActionPerformed(evt);
            }
        });
        transaksiMenu.add(menuItemTransaksiGaji);

        menuBar.add(transaksiMenu);

        reportMenu.setText("Report");

        menuItemSlipGajiReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemSlipGajiReport.setText("Report Slip Gaji");
        menuItemSlipGajiReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSlipGajiReportActionPerformed(evt);
            }
        });
        reportMenu.add(menuItemSlipGajiReport);

        menuItemLaporanGajiTotalReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemLaporanGajiTotalReport.setText("Report Laporan Gaji Total");
        menuItemLaporanGajiTotalReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLaporanGajiTotalReportActionPerformed(evt);
            }
        });
        reportMenu.add(menuItemLaporanGajiTotalReport);

        menuItemRekapPresensi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemRekapPresensi.setText("Report Rekap Presensi");
        menuItemRekapPresensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRekapPresensiActionPerformed(evt);
            }
        });
        reportMenu.add(menuItemRekapPresensi);

        menuItemPayrollBank.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemPayrollBank.setText("Report Payroll Bank");
        menuItemPayrollBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPayrollBankActionPerformed(evt);
            }
        });
        reportMenu.add(menuItemPayrollBank);

        menuItemHistoryGajiReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemHistoryGajiReport.setText("Report History Gaji");
        menuItemHistoryGajiReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHistoryGajiReportActionPerformed(evt);
            }
        });
        reportMenu.add(menuItemHistoryGajiReport);

        menuBar.add(reportMenu);

        masterMenu.setText("Master");

        menuItemMasterDepartment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterDepartment.setText("Master Department");
        menuItemMasterDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterDepartmentActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterDepartment);

        menuItemMasterGolongan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterGolongan.setText("Master Golongan");
        menuItemMasterGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterGolonganActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterGolongan);

        menuItemMasterOutlet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterOutlet.setText("Master Outlet");
        menuItemMasterOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterOutletActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterOutlet);

        menuItemMasterPosisi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterPosisi.setText("Master Posisi");
        menuItemMasterPosisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterPosisiActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterPosisi);

        menuItemMasterShift.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterShift.setText("Master Shift");
        menuItemMasterShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterShiftActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterShift);

        menuItemMasterGroupShift.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterGroupShift.setText("Master Group Shift");
        menuItemMasterGroupShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterGroupShiftActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterGroupShift);

        menuItemMasterStatus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterStatus.setText("Master Status");
        menuItemMasterStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterStatusActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterStatus);

        menuItemMasterKaryawan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterKaryawan.setText("Master Karyawan");
        menuItemMasterKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterKaryawanActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterKaryawan);

        menuItemMasterLiburNasional.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterLiburNasional.setText("Master Libur Nasional");
        menuItemMasterLiburNasional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterLiburNasionalActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterLiburNasional);

        menuItemMasterLiburPerusahaan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemMasterLiburPerusahaan.setText("Master Libur Perusahaan");
        menuItemMasterLiburPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMasterLiburPerusahaanActionPerformed(evt);
            }
        });
        masterMenu.add(menuItemMasterLiburPerusahaan);

        menuBar.add(masterMenu);
        menuBar.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuBar.add(jMenuItem2);

        jMenuBar1.add(menuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1040)/2, (screenSize.height-718)/2, 1040, 718);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemTransaksiPresensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTransaksiPresensiActionPerformed
        // TODO add your handling code here:         
        if (!rekapPresensiForm.isVisible()) {
            rekapPresensiForm.setVisible(true);
            menuItemTransaksiPresensi.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemTransaksiPresensiActionPerformed

    private void menuItemTransaksiGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTransaksiGajiActionPerformed
        // TODO add your handling code here:
        if (!transaksiDepartmentForm.isVisible()) {
            transaksiDepartmentForm.setVisible(true);
            menuItemTransaksiGaji.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemTransaksiGajiActionPerformed

    private void menuItemPayrollBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPayrollBankActionPerformed
        // TODO add your handling code here:
        if (!payrollBankReportForm.isVisible()) {
            payrollBankReportForm.setVisible(true);
            menuItemPayrollBank.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemPayrollBankActionPerformed

    private void menuItemLaporanGajiTotalReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLaporanGajiTotalReportActionPerformed
        // TODO add your handling code here:
        if (!transaksiGajiDepartmentReportForm.isVisible()) {
            transaksiGajiDepartmentReportForm.setVisible(true);
            menuItemLaporanGajiTotalReport.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemLaporanGajiTotalReportActionPerformed

    private void menuItemMasterGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterGolonganActionPerformed
        // TODO add your handling code here:
        if (!golonganForm.isVisible()) {
            golonganForm.setVisible(true);
            menuItemMasterGolongan.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemMasterGolonganActionPerformed

    private void menuItemMasterShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterShiftActionPerformed
        // TODO add your handling code here:
        if (!shiftForm.isVisible()) {
            shiftForm.setVisible(true);
            menuItemMasterShift.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemMasterShiftActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuItemSlipGajiReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSlipGajiReportActionPerformed
        // TODO add your handling code here:
        if (!gajiPerKaryawanReportForm.isVisible()) {
            gajiPerKaryawanReportForm.setVisible(true);
            menuItemSlipGajiReport.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemSlipGajiReportActionPerformed

    private void menuItemRekapPresensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRekapPresensiActionPerformed
        // TODO add your handling code here:
        if (!rekapPresensiPerBulanForm.isVisible()) {
            rekapPresensiPerBulanForm.setVisible(true);
            menuItemRekapPresensi.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemRekapPresensiActionPerformed

    private void menuItemHistoryGajiReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHistoryGajiReportActionPerformed
        // TODO add your handling code here:
        if (!rekapGajiForm.isVisible()) {
            rekapGajiForm.setVisible(true);
        }
    }//GEN-LAST:event_menuItemHistoryGajiReportActionPerformed

    private void menuItemMasterDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterDepartmentActionPerformed
        // TODO add your handling code here:
        if (!departmentForm.isVisible()) {
            departmentForm.setVisible(true);
            menuItemMasterDepartment.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemMasterDepartmentActionPerformed

    private void menuItemMasterOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterOutletActionPerformed
        // TODO add your handling code here:
        if (!outletForm.isVisible()) {
            outletForm.setVisible(true);
            menuItemMasterOutlet.setEnabled(true);
        }
    }//GEN-LAST:event_menuItemMasterOutletActionPerformed

    private void menuItemMasterPosisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterPosisiActionPerformed
        // TODO add your handling code here:
        if (!posisiForm.isVisible()) {
            posisiForm.setVisible(true);
            menuItemMasterPosisi.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemMasterPosisiActionPerformed

    private void menuItemMasterGroupShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterGroupShiftActionPerformed
        // TODO add your handling code here:
        if (!groupShiftForm.isVisible()) {
            groupShiftForm.setVisible(true);
            menuItemMasterGroupShift.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemMasterGroupShiftActionPerformed

    private void menuItemMasterStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterStatusActionPerformed
        // TODO add your handling code here:
        if (!statusSettingForm.isVisible()) {
            statusSettingForm.setVisible(true);
            menuItemMasterStatus.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemMasterStatusActionPerformed

    private void menuItemMasterKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterKaryawanActionPerformed
        // TODO add your handling code here:
        if (!karyawanForm.isVisible()) {
            karyawanForm.setVisible(true);
            menuItemMasterKaryawan.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemMasterKaryawanActionPerformed

    private void menuItemMasterLiburNasionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterLiburNasionalActionPerformed
        // TODO add your handling code here:
        if (!liburNasionalForm.isVisible()) {
            liburNasionalForm.setVisible(true);
            menuItemMasterLiburNasional.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemMasterLiburNasionalActionPerformed

    private void menuItemMasterLiburPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasterLiburPerusahaanActionPerformed
        // TODO add your handling code here:
        if (!liburPerusahaanForm.isVisible()) {
            liburPerusahaanForm.setVisible(true);
            menuItemMasterLiburPerusahaan.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemMasterLiburPerusahaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu masterMenu;
    private javax.swing.JMenu menuBar;
    private javax.swing.JMenuItem menuItemHistoryGajiReport;
    private javax.swing.JMenuItem menuItemLaporanGajiTotalReport;
    private javax.swing.JMenuItem menuItemMasterDepartment;
    private javax.swing.JMenuItem menuItemMasterGolongan;
    private javax.swing.JMenuItem menuItemMasterGroupShift;
    private javax.swing.JMenuItem menuItemMasterKaryawan;
    private javax.swing.JMenuItem menuItemMasterLiburNasional;
    private javax.swing.JMenuItem menuItemMasterLiburPerusahaan;
    private javax.swing.JMenuItem menuItemMasterOutlet;
    private javax.swing.JMenuItem menuItemMasterPosisi;
    private javax.swing.JMenuItem menuItemMasterShift;
    private javax.swing.JMenuItem menuItemMasterStatus;
    private javax.swing.JMenuItem menuItemPayrollBank;
    private javax.swing.JMenuItem menuItemRekapPresensi;
    private javax.swing.JMenuItem menuItemSlipGajiReport;
    private javax.swing.JMenuItem menuItemTransaksiGaji;
    private javax.swing.JMenuItem menuItemTransaksiPresensi;
    private javax.swing.JLabel picLabel;
    private javax.swing.JMenu reportMenu;
    private javax.swing.JMenu transaksiMenu;
    // End of variables declaration//GEN-END:variables
}
