/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.presensikaryawan.detailtransaksidepartment;


import com.presensikaryawan.tools.DaoFactory;
import com.presensikaryawan.transaksiDepartment.TransaksiDepartment;
import com.presensikaryawan.transaksiDepartment.TransaksiDepartmentTableModel;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Tinus
 */
public class DetailLainDialog extends javax.swing.JDialog {
    
    int bln;
    int thn;
    JTable presensiTable;
    String kode_department;

    /**
     * Creates new form DetailLainDialog
     */
    public DetailLainDialog(java.awt.Frame parent, boolean modal, String nip, String nama, int bulan, int tahun, JTable presensiTable, String kodeDepartment) throws SQLException {
        super(parent, modal);
        initComponents();
        nilaiNamaLabel.setText(nama);
        nilaiNIPLabel.setText(nip);
        if(bulan<10)
        nilaiTanggalLabel.setText(tahun+"-0"+bulan);
        else
            nilaiTanggalLabel.setText(tahun+"-"+bulan);
        this.presensiTable=presensiTable;
        this.kode_department=kodeDepartment;
        bln=bulan;
        thn=tahun;
//        this.kode_department=kode_department;
//        List<DetailLain> detailLains = DaoFactory.getPresensiTidakMasukDao().getDetailPresensiByNIP(nip, bulan, tahun);
//        DetailLainTableModel model=new DetailLainTableModel(detailPresensis);
//        detailPresensiTableModel.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        nipLabel = new javax.swing.JLabel();
        nilaiNamaLabel = new javax.swing.JLabel();
        nilaiNIPLabel = new javax.swing.JLabel();
        tanggalLabel = new javax.swing.JLabel();
        Potongan = new javax.swing.JLabel();
        potonganTextField = new javax.swing.JTextField();
        tablePanel = new javax.swing.JScrollPane();
        updateButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        nilaiTanggalLabel = new javax.swing.JLabel();
        kembaliButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        namaLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        namaLabel.setText("Nama");

        nipLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        nipLabel.setText("NIP");

        nilaiNamaLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        nilaiNamaLabel.setText("nilai Nama");

        nilaiNIPLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        nilaiNIPLabel.setText("nilai NIP");

        tanggalLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        tanggalLabel.setText("Bulan");

        Potongan.setFont(new java.awt.Font("Dialog", 0, 12));
        Potongan.setText("Potongan");

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/24/Edit.gif"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        batalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/24/Exit.gif"))); // NOI18N
        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        nilaiTanggalLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        nilaiTanggalLabel.setText("-");

        kembaliButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/24/Left.gif"))); // NOI18N
        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nipLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(namaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(tanggalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nilaiNamaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nilaiNIPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addComponent(nilaiTanggalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addGap(239, 239, 239)
                                .addComponent(Potongan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(potonganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtamaLayout.createSequentialGroup()
                        .addComponent(kembaliButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                        .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton)))
                .addContainerGap())
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilaiNamaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilaiNIPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(potonganTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(Potongan, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(tanggalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(nilaiTanggalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(batalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kembaliButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-749)/2, (screenSize.height-533)/2, 749, 533);
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
if (!nilaiTanggalLabel.getText().matches("-") && potonganTextField.getText() != null) {
//            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = nilaiTanggalLabel.getText();
//            tanggal = tanggal.substring(6, 10)+"-"+tanggal.substring(3, 5)+"%";
//            System.out.println(tanggal);
//            Date date = null;
//            try {
//                date = dateFormat.parse(tanggal);
//                System.out.println(date);
//            } catch (ParseException ex) {
//                Logger.getLogger(DetailLainDialog.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            tanggal = dateFormat.format(date);
//            System.out.println(tanggal);
            String nip = nilaiNIPLabel.getText();
            try {
                System.out.println("masuk");
                DaoFactory.getTransaksiDepartmentDao().updatePotongan(nip, tanggal, Double.parseDouble(potonganTextField.getText()));
//                List<DetailLain> detailPresensis = DaoFactory.getDetailLainDao().getDetailPresensiByNIP(nip, bln, thn);
//                DetailLainTableModel model=new DetailLainTableModel(detailPresensis);
//                detailPresensiTableModel.setModel(model);
                List<TransaksiDepartment> transaksi = DaoFactory.getTransaksiDepartmentDao().getAllTransaksiDepartment(kode_department, bln, thn);
                 TransaksiDepartmentTableModel model = new TransaksiDepartmentTableModel(transaksi);
                 presensiTable.setModel(model);
                 
//        List<TransaksiDepartment> transaksiDepartments = dao.getAllTransaksiDepartment(department, maxDayOfMonth);
//        
//        TransaksiDepartmentTableModel model = new TransaksiDepartmentTableModel(transaksiDepartments);
//        karyawanTable1.setModel(model);


            } catch (SQLException ex) {
                ex.getMessage();
            }
        } else {
            JOptionPane.showMessageDialog(this, "<html><font color=#FF0000>" + "Tanggal dan Keterangan Harus Diisi" + "</font></html>", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        // TODO add your handling code here:
        nilaiNIPLabel.setText(null);
        nilaiTanggalLabel.setText("-");
    }//GEN-LAST:event_batalButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_kembaliButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Potongan;
    private javax.swing.JButton batalButton;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel nilaiNIPLabel;
    private javax.swing.JLabel nilaiNamaLabel;
    private javax.swing.JLabel nilaiTanggalLabel;
    private javax.swing.JLabel nipLabel;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTextField potonganTextField;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
