package com.presensikaryawan.transaksi;

import com.dssystem.umum.ComponentFocus;
import com.presensikaryawan.departmentSetting.Department;
import com.presensikaryawan.golongan.Golongan;
import com.presensikaryawan.karyawan.Karyawan;
import com.presensikaryawan.posisi.*;
import com.presensikaryawan.shiftSetting.Shift;
import com.presensikaryawan.tools.DaoFactory;
import com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/*
 * masterInventoryGrup.java
 *
 * Created on October 21, 2006, 10:06 AM
 */
/**
 *
 * @author Als
 */
public class TransaksiGajiForm extends javax.swing.JFrame {

    private DaoFactory service;
    private Posisi activePosisi;
    private String kode_golongan, kode_department, nip, nama;

    /**
     * Creates new form masterInventoryGrup
     */
    public TransaksiGajiForm() throws SQLException {
        initComponents();
        UIManager.put("nimbusBase", new Color(204, 204, 255));

        initComponentFocus();

        if (departmentCombo.getSelectedItem() == null) {
            kode_department = "%";
        } else {
            kode_department = String.valueOf(departmentCombo.getSelectedItem());
        }
        if (golonganCombo.getSelectedItem() == null) {
            kode_golongan = "%";
        } else {
            kode_golongan = "%" + String.valueOf(golonganCombo.getSelectedItem());
        }
        if (nipKaryawanCombo.getSelectedItem() == null) {
            nip = "%";
        } else {
            nip = "%" + String.valueOf(nipKaryawanCombo.getSelectedItem());
        }
        if (namaKaryawanCombo.getSelectedItem() == null) {
            nama = "%";
        } else {
            nama = "%" + String.valueOf(namaKaryawanCombo.getSelectedItem());
        }

        List<Department> departments = DaoFactory.getTransaksiGajiDao().getAllDepartmentCodeByAnything(nip, nama);
//        List<Shift> shifts = DaoFactory.getTransaksiGajiDao().getWaktuMulaiDanSelesaiByDepartment(kode_department);
        List<Karyawan> karyawans = DaoFactory.getTransaksiGajiDao().getNamaDanNIPKaryawanByAnything(kode_department, kode_golongan, nama);
        for (Karyawan k : karyawans) {
            nipKaryawanCombo.addItem(k.getNip());
            namaKaryawanCombo.addItem(k.getNama());
            golonganCombo.addItem(k.getKodeGolongan());
        }
        List<Golongan> golongans = DaoFactory.getTransaksiGajiDao().getGolonganByNIPOrNama(nama, nip);
        for (Golongan g : golongans) {
            golonganCombo.addItem(g.getKodeGolongan());
        }
        for (Department d : departments) {
            departmentCombo.addItem(d.getKodeDepartment());
        }
        String bulan = String.valueOf(monthChooser.getMonth());
        String tahun = String.valueOf(yearChooser.getYear());
        String bulanTahun = tahun + "-0" + bulan + "-%";
        System.out.println(bulanTahun);
        String nip2 = "%";
        List<PresensiKaryawan> presensiKaryawans = DaoFactory.getTransaksiGajiDao().getPresensiByMonth(bulanTahun, nip2);
        PresensiTableModel model = new PresensiTableModel(presensiKaryawans);
        presenstiTable.setModel(model);
        System.out.println(monthChooser.getMonth() + ",year " + yearChooser.getYear());
    }

    private void initComponentFocus() {
        departmentCombo.addFocusListener(new ComponentFocus(departmentCombo));
        golonganCombo.addFocusListener(new ComponentFocus(golonganCombo));
        nipKaryawanCombo.addFocusListener(new ComponentFocus(nipKaryawanCombo));
        namaKaryawanCombo.addFocusListener(new ComponentFocus(namaKaryawanCombo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        headPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        fungsiLabel = new javax.swing.JLabel();
        panelStatus1 = new com.sistem.panelstatus.PanelStatus();
        cmdKeluar = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        bulanLabel = new javax.swing.JLabel();
        monthChooser = new com.toedter.calendar.JMonthChooser();
        yearChooser = new com.toedter.calendar.JYearChooser();
        departmentLabel = new javax.swing.JLabel();
        departmentCombo = new javax.swing.JComboBox();
        golonganCombo = new javax.swing.JComboBox();
        golonganLabel = new javax.swing.JLabel();
        namaKaryawanLabel = new javax.swing.JLabel();
        namaKaryawanCombo = new javax.swing.JComboBox();
        nipKaryawanCombo = new javax.swing.JComboBox();
        nipKaryawanLabel = new javax.swing.JLabel();
        posisiPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        presenstiTable = new javax.swing.JTable();
        resultPanel = new javax.swing.JPanel();
        terlambatLabel = new javax.swing.JLabel();
        tidakMasukLabel = new javax.swing.JLabel();
        buttonKlarifikasi = new javax.swing.JButton();
        buttonKlarifikasi1 = new javax.swing.JButton();
        terlambatLabel2 = new javax.swing.JLabel();
        nilaiTerlambatLabel = new javax.swing.JLabel();
        nilaiTidakMasukLabel = new javax.swing.JLabel();
        nilaiLembur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Kategori");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jDesktopPane1.setBackground(new java.awt.Color(153, 255, 153));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        headPanel.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logosimtel.jpg"))); // NOI18N

        menuLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menuLabel.setText("Menu Transaksi Gaji Karyawan");

        fungsiLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fungsiLabel.setText("Digunakan menghitung transaksi gaji & rekap karyawan per bulan/per tahun");

        org.jdesktop.layout.GroupLayout headPanelLayout = new org.jdesktop.layout.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(headPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(logoLabel)
                .add(4, 4, 4)
                .add(headPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(menuLabel)
                    .add(fungsiLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 437, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(519, Short.MAX_VALUE))
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(headPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(headPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(logoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(headPanelLayout.createSequentialGroup()
                        .add(menuLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fungsiLabel)))
                .addContainerGap())
        );

        headPanel.setBounds(0, 0, 1020, 77);
        jDesktopPane1.add(headPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelStatus1.setBounds(0, 650, 1020, 50);
        jDesktopPane1.add(panelStatus1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmdKeluar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmdKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/24/Printer.gif"))); // NOI18N
        cmdKeluar.setText("Cetak");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });
        cmdKeluar.setBounds(900, 610, 110, 40);
        jDesktopPane1.add(cmdKeluar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        inputPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bulanLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bulanLabel.setText("Bulan :");

        departmentLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        departmentLabel.setText("Department");

        departmentCombo.setEditable(true);
        departmentCombo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        departmentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboActionPerformed(evt);
            }
        });
        departmentCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                departmentComboKeyPressed(evt);
            }
        });

        golonganCombo.setEditable(true);
        golonganCombo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        golonganCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                golonganComboActionPerformed(evt);
            }
        });
        golonganCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                golonganComboKeyPressed(evt);
            }
        });

        golonganLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        golonganLabel.setText("Golongan");

        namaKaryawanLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        namaKaryawanLabel.setText("Nama Karyawan");

        namaKaryawanCombo.setEditable(true);
        namaKaryawanCombo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        namaKaryawanCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKaryawanComboActionPerformed(evt);
            }
        });
        namaKaryawanCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaKaryawanComboKeyPressed(evt);
            }
        });

        nipKaryawanCombo.setEditable(true);
        nipKaryawanCombo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        nipKaryawanCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nipKaryawanComboActionPerformed(evt);
            }
        });
        nipKaryawanCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nipKaryawanComboKeyPressed(evt);
            }
        });

        nipKaryawanLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nipKaryawanLabel.setText("NIP");

        org.jdesktop.layout.GroupLayout inputPanelLayout = new org.jdesktop.layout.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(nipKaryawanLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(namaKaryawanLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(golonganLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(departmentLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(inputPanelLayout.createSequentialGroup()
                        .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(golonganCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(namaKaryawanCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nipKaryawanCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(inputPanelLayout.createSequentialGroup()
                        .add(departmentCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(471, 471, 471)
                        .add(bulanLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(18, 18, 18)
                        .add(monthChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(yearChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(45, 45, 45))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(bulanLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(monthChooser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(yearChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(departmentLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(departmentCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(golonganLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(golonganCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(namaKaryawanLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(namaKaryawanCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nipKaryawanLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nipKaryawanCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        inputPanel.setBounds(0, 70, 1020, 170);
        jDesktopPane1.add(inputPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        posisiPanel.setBackground(new java.awt.Color(204, 204, 204));
        posisiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Posisi"));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        presenstiTable.setAutoCreateRowSorter(true);
        presenstiTable.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        presenstiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIP", "Nama Karyawan", "Tanggal", "Waktu Mulai", "Waktu Selesai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        presenstiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                presenstiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(presenstiTable);

        org.jdesktop.layout.GroupLayout posisiPanelLayout = new org.jdesktop.layout.GroupLayout(posisiPanel);
        posisiPanel.setLayout(posisiPanelLayout);
        posisiPanelLayout.setHorizontalGroup(
            posisiPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        posisiPanelLayout.setVerticalGroup(
            posisiPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(posisiPanelLayout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        posisiPanel.setBounds(0, 240, 1020, 250);
        jDesktopPane1.add(posisiPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        resultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        terlambatLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        terlambatLabel.setText("Terlambat             :");

        tidakMasukLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tidakMasukLabel.setText("Tidak Masuk         :");

        buttonKlarifikasi.setText("Klarifikasi");

        buttonKlarifikasi1.setText("Klarifikasi");

        terlambatLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        terlambatLabel2.setText("Lembur         :");

        nilaiTerlambatLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nilaiTerlambatLabel.setText("nilai terlambat");

        nilaiTidakMasukLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nilaiTidakMasukLabel.setText("nilai tidak masuk");

        nilaiLembur.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nilaiLembur.setText("nilai lembur");

        org.jdesktop.layout.GroupLayout resultPanelLayout = new org.jdesktop.layout.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(resultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(tidakMasukLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .add(terlambatLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(resultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(resultPanelLayout.createSequentialGroup()
                        .add(nilaiTerlambatLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .add(47, 47, 47))
                    .add(resultPanelLayout.createSequentialGroup()
                        .add(nilaiTidakMasukLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(resultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(buttonKlarifikasi1)
                    .add(resultPanelLayout.createSequentialGroup()
                        .add(buttonKlarifikasi)
                        .add(117, 117, 117)
                        .add(terlambatLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nilaiLembur)))
                .add(414, 414, 414))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(resultPanelLayout.createSequentialGroup()
                .add(resultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(terlambatLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonKlarifikasi)
                    .add(terlambatLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nilaiTerlambatLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nilaiLembur, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(resultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(resultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(tidakMasukLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(nilaiTidakMasukLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(buttonKlarifikasi1))
                .add(0, 41, Short.MAX_VALUE))
        );

        resultPanel.setBounds(0, 490, 1020, 120);
        jDesktopPane1.add(resultPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("");
        jDesktopPane1.getAccessibleContext().setAccessibleDescription("");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1036)/2, (screenSize.height-738)/2, 1036, 738);
    }// </editor-fold>//GEN-END:initComponents

    private void presenstiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presenstiTableMouseClicked
        int row = presenstiTable.getSelectedRow();
        String kodegroup = presenstiTable.getValueAt(row, 0).toString();
        String namagroup = presenstiTable.getValueAt(row, 1).toString();

    }//GEN-LAST:event_presenstiTableMouseClicked
    private void isitable() {
    }

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed

        this.dispose();
}//GEN-LAST:event_cmdKeluarActionPerformed

    private void departmentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboActionPerformed
        // TODO add your handling code here:
        kode_department = "%" + String.valueOf(departmentCombo.getSelectedItem());
        if (kode_department != null) {

            if (departmentCombo.getSelectedItem() == null) {
                kode_department = "%";
            } else {
                kode_department = String.valueOf(departmentCombo.getSelectedItem());
            }
            if (golonganCombo.getSelectedItem() == null) {
                kode_golongan = "%";
            } else {
                kode_golongan = "%" + String.valueOf(golonganCombo.getSelectedItem());
            }

            if (namaKaryawanCombo.getSelectedItem() == null) {
                nama = "%";
            } else {
                nama = "%" + String.valueOf(namaKaryawanCombo.getSelectedItem());
            }
            departmentCombo.removeAllItems();
            namaKaryawanCombo.removeAllItems();
            golonganCombo.removeAllItems();
            nipKaryawanCombo.removeAllItems();
            try {
                List<Golongan> golongans = DaoFactory.getTransaksiGajiDao().getGolonganByNIPOrNama(nama, nip);
                for (Golongan g : golongans) {
                    golonganCombo.addItem(g.getKodeGolongan());
                }
                List<Department> departments = DaoFactory.getTransaksiGajiDao().getAllDepartmentCodeByAnything(nip, nama);
                for (Department d : departments) {
                    departmentCombo.addItem(d.getKodeDepartment());
                }
                List<Karyawan> karyawans = DaoFactory.getTransaksiGajiDao().getNamaDanNIPKaryawanByAnything(kode_department, kode_golongan, nama);
                for (Karyawan k : karyawans) {
                    nipKaryawanCombo.addItem(k.getNip());
                    namaKaryawanCombo.addItem(k.getNama());
                }

            } catch (SQLException ex) {
                Logger.getLogger(TransaksiGajiForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_departmentComboActionPerformed

    private void departmentComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departmentComboKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentComboKeyPressed

    private void golonganComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_golonganComboActionPerformed
        // TODO add your handling code here:
        kode_golongan = "%" + String.valueOf(golonganCombo.getSelectedItem());
        if (kode_golongan != null) {

            if (departmentCombo.getSelectedItem() == null) {
                kode_department = "%";
            } else {
                kode_department = String.valueOf(departmentCombo.getSelectedItem());
            }
            if (golonganCombo.getSelectedItem() == null) {
                kode_golongan = "%";
            } else {
                kode_golongan = "%" + String.valueOf(golonganCombo.getSelectedItem());
            }

            if (namaKaryawanCombo.getSelectedItem() == null) {
                nama = "%";
            } else {
                nama = "%" + String.valueOf(namaKaryawanCombo.getSelectedItem());
            }
            departmentCombo.removeAllItems();
            namaKaryawanCombo.removeAllItems();
            golonganCombo.removeAllItems();
            nipKaryawanCombo.removeAllItems();
            try {
                List<Golongan> golongans = DaoFactory.getTransaksiGajiDao().getGolonganByNIPOrNama(nama, nip);
                for (Golongan g : golongans) {
                    golonganCombo.addItem(g.getKodeGolongan());
                }
                List<Department> departments = DaoFactory.getTransaksiGajiDao().getAllDepartmentCodeByAnything(nip, nama);
                for (Department d : departments) {
                    departmentCombo.addItem(d.getKodeDepartment());
                }
                List<Karyawan> karyawans = DaoFactory.getTransaksiGajiDao().getNamaDanNIPKaryawanByAnything(kode_department, kode_golongan, nama);
                for (Karyawan k : karyawans) {
                    nipKaryawanCombo.addItem(k.getNip());
                    namaKaryawanCombo.addItem(k.getNama());
                }

            } catch (SQLException ex) {
                Logger.getLogger(TransaksiGajiForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_golonganComboActionPerformed

    private void golonganComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_golonganComboKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_golonganComboKeyPressed

    private void namaKaryawanComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKaryawanComboKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKaryawanComboKeyPressed

    private void nipKaryawanComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nipKaryawanComboActionPerformed
        nip = "%" + String.valueOf(nipKaryawanCombo.getSelectedItem());
        if (nip != null) {

            if (departmentCombo.getSelectedItem() == null) {
                kode_department = "%";
            } else {
                kode_department = String.valueOf(departmentCombo.getSelectedItem());
            }
            if (golonganCombo.getSelectedItem() == null) {
                kode_golongan = "%";
            } else {
                kode_golongan = "%" + String.valueOf(golonganCombo.getSelectedItem());
            }

            if (namaKaryawanCombo.getSelectedItem() == null) {
                nama = "%";
            } else {
                nama = "%" + String.valueOf(namaKaryawanCombo.getSelectedItem());
            }
            departmentCombo.removeAllItems();
            namaKaryawanCombo.removeAllItems();
            golonganCombo.removeAllItems();
            nipKaryawanCombo.removeAllItems();
            try {
                List<Golongan> golongans = DaoFactory.getTransaksiGajiDao().getGolonganByNIPOrNama(nama, nip);
                for (Golongan g : golongans) {
                    golonganCombo.addItem(g.getKodeGolongan());
                }
                List<Department> departments = DaoFactory.getTransaksiGajiDao().getAllDepartmentCodeByAnything(nip, nama);
                for (Department d : departments) {
                    departmentCombo.addItem(d.getKodeDepartment());
                }
                List<Karyawan> karyawans = DaoFactory.getTransaksiGajiDao().getNamaDanNIPKaryawanByAnything(kode_department, kode_golongan, nama);
                for (Karyawan k : karyawans) {
                    nipKaryawanCombo.addItem(k.getNip());
                    namaKaryawanCombo.addItem(k.getNama());
                }

            } catch (SQLException ex) {
                Logger.getLogger(TransaksiGajiForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_nipKaryawanComboActionPerformed

    private void nipKaryawanComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nipKaryawanComboKeyPressed
        if (evt.getKeyCode() == 10) {
        }
    }//GEN-LAST:event_nipKaryawanComboKeyPressed

    private void namaKaryawanComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKaryawanComboActionPerformed
        // TODO add your handling code here:
        nama = "%" + String.valueOf(namaKaryawanCombo.getSelectedItem());
        if (nama != null) {

            if (departmentCombo.getSelectedItem() == null) {
                kode_department = "%";
            } else {
                kode_department = String.valueOf(departmentCombo.getSelectedItem());
            }
            if (golonganCombo.getSelectedItem() == null) {
                kode_golongan = "%";
            } else {
                kode_golongan = "%" + String.valueOf(golonganCombo.getSelectedItem());
            }

            if (namaKaryawanCombo.getSelectedItem() == null) {
                nama = "%";
            } else {
                nama = "%" + String.valueOf(namaKaryawanCombo.getSelectedItem());
            }
            departmentCombo.removeAllItems();
            namaKaryawanCombo.removeAllItems();
            golonganCombo.removeAllItems();
            nipKaryawanCombo.removeAllItems();
            try {
                List<Golongan> golongans = DaoFactory.getTransaksiGajiDao().getGolonganByNIPOrNama(nama, nip);
                for (Golongan g : golongans) {
                    golonganCombo.addItem(g.getKodeGolongan());
                }
                List<Department> departments = DaoFactory.getTransaksiGajiDao().getAllDepartmentCodeByAnything(nip, nama);
                for (Department d : departments) {
                    departmentCombo.addItem(d.getKodeDepartment());
                }
                List<Karyawan> karyawans = DaoFactory.getTransaksiGajiDao().getNamaDanNIPKaryawanByAnything(kode_department, kode_golongan, nama);
                for (Karyawan k : karyawans) {
                    nipKaryawanCombo.addItem(k.getNip());
                    namaKaryawanCombo.addItem(k.getNama());
                }

            } catch (SQLException ex) {
                Logger.getLogger(TransaksiGajiForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_namaKaryawanComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            //UIManager.setLookAndFeel(new smooth.windows.SmoothLookAndFeel());

        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TransaksiGajiForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new TransaksiGajiForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiGajiForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bulanLabel;
    private javax.swing.JButton buttonKlarifikasi;
    private javax.swing.JButton buttonKlarifikasi1;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JComboBox departmentCombo;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel fungsiLabel;
    private javax.swing.JComboBox golonganCombo;
    private javax.swing.JLabel golonganLabel;
    private javax.swing.JPanel headPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel menuLabel;
    private com.toedter.calendar.JMonthChooser monthChooser;
    private javax.swing.JComboBox namaKaryawanCombo;
    private javax.swing.JLabel namaKaryawanLabel;
    private javax.swing.JLabel nilaiLembur;
    private javax.swing.JLabel nilaiTerlambatLabel;
    private javax.swing.JLabel nilaiTidakMasukLabel;
    private javax.swing.JComboBox nipKaryawanCombo;
    private javax.swing.JLabel nipKaryawanLabel;
    private com.sistem.panelstatus.PanelStatus panelStatus1;
    private javax.swing.JPanel posisiPanel;
    private javax.swing.JTable presenstiTable;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel terlambatLabel;
    private javax.swing.JLabel terlambatLabel2;
    private javax.swing.JLabel tidakMasukLabel;
    private com.toedter.calendar.JYearChooser yearChooser;
    // End of variables declaration//GEN-END:variables
}
